# Generated by Django 3.2.7 on 2021-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.CharField(default='', max_length=1000000)),
            ],
            options={
                'verbose_name': 'Vote',
            },
        ),
    ]
