# Generated by Django 3.2.7 on 2021-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datastore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.CharField(default='', max_length=3000)),
                ('Threshold', models.IntegerField(default=1)),
                ('Candidates', models.CharField(default='', max_length=10000)),
            ],
            options={
                'verbose_name': 'Admin Database',
            },
        ),
    ]
