# Generated by Django 3.2.7 on 2021-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_c_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.CharField(default='', max_length=2000)),
                ('Category', models.CharField(default='', max_length=2000)),
            ],
            options={
                'verbose_name': 'Add Candidates',
            },
        ),
    ]
