# Generated by Django 3.2.7 on 2021-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_c_model',
            name='Votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add_c_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
